version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: "dota-chooser"
      POSTGRES_USER: "dayadanya"
      POSTGRES_PASSWORD: "dayadanya"
    ports:
      - "5433:5432"

    